
include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  errors:
    constant_identifier_names: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
  plugins:
    - custom_lint
    
    



